### ISSUE TITLE
integration tests unstable

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#124]
After merging the pull-request https://github.com/oasp/oasp4j-sample/pull/43 the integration tests are now active. However, there is some problem causing them to hang from my test. We will see what jenkins will say about this. My local maven build said:

```
[INFO] [talledLocalContainer] SEVERE: The web application [/oasp4j-example-appli
cation] created a ThreadLocal with key of type [com.sun.xml.bind.v2.runtime.Coor
dinator$1] (value [com.sun.xml.bind.v2.runtime.Coordinator$1@a474c2]) and a valu
e of type [java.lang.Object[]] (value [[Ljava.lang.Object;@ed826d]) but failed t
o remove it when the web application was stopped. Threads are going to be renewe
d over time to try and avoid a probable memory leak.
[INFO] [talledLocalContainer] Nov 21, 2014 5:33:25 PM org.apache.catalina.startu
p.HostConfig deployDirectory
[INFO] [talledLocalContainer] INFO: Deploying web application directory C:\Proje
kte\oasp\workspaces\master\oasp4j-sample\oasp4j-example-application-integration-
test\target\cargo\configurations\tomcat7x\webapps\host-manager
[INFO] [talledLocalContainer] Nov 21, 2014 5:33:25 PM org.apache.catalina.startu
p.HostConfig deployDirectory
[INFO] [talledLocalContainer] INFO: Deploying web application directory C:\Proje
kte\oasp\workspaces\master\oasp4j-sample\oasp4j-example-application-integration-
test\target\cargo\configurations\tomcat7x\webapps\manager
[INFO] [talledLocalContainer] Nov 21, 2014 5:33:26 PM org.apache.coyote.Abstract
Protocol start
[INFO] [talledLocalContainer] INFO: Starting ProtocolHandler ["ajp-bio-8009"]
[INFO] [talledLocalContainer] Nov 21, 2014 5:33:26 PM org.apache.catalina.startu
p.Catalina start
[INFO] [talledLocalContainer] INFO: Server startup in 16059 ms
[INFO] [yer.DeployerWatchdog] Deployable [http://localhost:8081/cargocpc/index.h
tml] failed to finish deploying within the timeout period [120000]. The Deployab
le state is thus unknown.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] oasp4j-example ..................................... SUCCESS [  1.796 s]
[INFO] oasp4j-example-application ......................... SUCCESS [ 35.091 s]
[INFO] oasp4j-example-application-integration-test ........ FAILURE [02:08 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Comment by hohwille** [comment]
At least some of the tests are not @Ignored anymore and also do run correctly in jenkins. That is already some progress :)

**Comment by hohwille** [comment]
I thought we now have solved the actual problem but not jenkins failed again. Can someone shed a light into this. Why did jenkins fail (404 errors)? 

Is this not deterministic? I think so. What is going on?

**Comment by julianmetzler** [comment]
There is a exception, when starting tomcat for integration tests:
Caused by: org.h2.jdbc.JdbcSQLException: Exception opening port "8143" (port may be in use), cause: "java.net.BindException: Address already in use" [90061-176]

I guess this is why the tests get a 404.

**Comment by sobkowiak** [comment]
I can find one process running on port `8143`

```
oaspuser@oasp-ci:~$ sudo netstat -a -p -e | grep 8143
tcp6       0      0 [::]:8143               [::]:*                  LISTEN      tomcat7    46145774    1625/java
```
 
The sample deployed on Tomcat rund the H2 database on this port

**Comment by sobkowiak** [comment]
The file `/usr/share/tomcat7/lib/config/env/application.properties`  contains following entry 

```
database.url = jdbc:h2:~/restaurant-db;INIT=create schema if not exists public
```

No port given, but `8143` is probably a standard H2 port.

**Comment by sobkowiak** [comment]
I have changed the `oasp.port.range`value in the nb job.

**Comment by sobkowiak** [comment]
The itests crashed now due to memory problem

```
`09:58:40.545 [main] DEBUG o.a.cxf.phase.PhaseInterceptorChain - Invoking handleMessage on interceptor org.apache.cxf.jaxrs.client.WebClient$ClientAsyncResponseInterceptor@29fb112c
09:58:40.549 [main] DEBUG o.s.t.annotation.ProfileValueUtils - Retrieved @ProfileValueSourceConfiguration [null] for test class [io.oasp.gastronomy.restaurant.offermanagement.services.OfferManagementRestServiceTest]
09:58:40.550 [main] DEBUG o.s.t.annotation.ProfileValueUtils - Retrieved ProfileValueSource type [class org.springframework.test.annotation.SystemProfileValueSource] for class [io.oasp.gastronomy.restaurant.offermanagement.services.OfferManagementRestServiceTest]
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000f8b80000, 47185920, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 47185920 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /var/lib/tomcat7/webapps/jenkins/jobs/oasp4j-dev-nb/workspace/oasp4j-samples/oasp4j-sample-server-integration/hs_err_pid18704.log

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by sobkowiak** [comment]
I have started the build and observed the memory usage on Linux machine. The machine runs out of resources quickly and the jvm can not allocate more memory. I propose to restart Tomcat or the whole machine

**Comment by sobkowiak** [comment]
> I thought we now have solved the actual problem but not jenkins failed again. Can someone shed a light into this. Why did jenkins fail (404 errors)? 

We have enabled itests some days ago (20.02). We have not started them in nb before so we had no problems. After enabling them again the database port from itests conflicted with the database port used by the sample deployed on Tomcat. It could be solved by redefining the port using `oasp.port.range`. But we have no memory problems.

**Comment by sobkowiak** [comment]
The problem is probably common with #181

**Comment by sobkowiak** [comment]
I have used an invasive solution

```
echo 1 > /proc/sys/vm/overcommit_memory
```
 
> overcommit_memory

> Controls overcommit of system memory, possibly allowing processes to allocate (but not use) more memory than is actually available.

> 0 - Heuristic overcommit handling. Obvious overcommits of address space are refused. Used for a typical system. It ensures a seriously wild allocation fails while allowing overcommit to reduce swap usage. root is allowed to allocate slighly more memory in this mode. This is the default.

> 1 - Always overcommit. Appropriate for some scientific applications.

> 2 - Don't overcommit. The total address space commit for the system is not permitted to exceed swap plus a configurable percentage (default is 50) of physical RAM. Depending on the percentage you use, in most situations this means a process will not be killed while attempting to use already-allocated memory but will receive errors on memory allocation as appropriate.


The build goes further and fails but the displayed log file is broken somewhere in the middle of oasp4j-sample-core test cases. I think we write too much in the logs. We don't need the DEBUG log level in test cases. Please decrease the level to INFO

**Comment by sobkowiak** [comment]
Decreasing the log size (fbf81b4b550582fa65cd7b96f2c5adeb527ee9f4) didn't help.

**Comment by sobkowiak** [comment]
After restart we have no more the problem with conflicting port and no more problems with memory allocation. I can see, each build increases the memory used by Tomcat. It means, we will have soon the same problem.

Actually the test cases can be run but some of them fail:

```
Results :

Failed tests: 
  TableManagementRestServiceTest.markTableAsTest:169 
Expected: is <OCCUPIED>
     but: was <RESERVED>
  TableManagementRestServiceTest.deleteTableTest:211 expected:<0> but was:<1>
  TableManagementRestServiceTest.createTableTest:190 expected:<1> but was:<0>

Tests in error: 
  OfferManagementRestServiceTest.isProductInUseTest:282->createDrink:104 » Forbidden
  OfferManagementRestServiceTest.findProductTest:247->createDrink:104 » Forbidden
  OfferManagementRestServiceTest.crudOfferTest:62->createDrink:104 » Forbidden H...
  OfferManagementRestServiceTest.updateProductTest:265 » Forbidden HTTP 403 Forb...
  TableManagementRestServiceTest.crudTableTest:53 » Forbidden HTTP 403 Forbidden
  SalesManagementRestServiceTest.doPaymentTest:212 » Forbidden HTTP 403 Forbidde...
  SalesManagementRestServiceTest.deleteBillTest:269 » Forbidden HTTP 403 Forbidd...
  SalesManagementRestServiceTest.updateOrderPositionTest:148 » Forbidden HTTP 40...

Tests run: 37, Failures: 3, Errors: 8, Skipped: 16
```

The most of them are probably caused by following error

```
[INFO] [talledLocalContainer] Caused by: org.springframework.security.access.AccessDeniedException: Access is denied
[INFO] [talledLocalContainer] 	at org.springframework.security.access.vote.UnanimousBased.decide(UnanimousBased.java:90) ~[spring-security-core-3.2.5.RELEASE.jar:3.2.5.RELEASE]
[INFO] [talledLocalContainer] 	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:206) ~[spring-security-core-3.2.5.RELEASE.jar:3.2.5.RELEASE]
[INFO] [talledLocalContainer] 	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:60) ~[spring-security-core-3.2.5.RELEASE.jar:3.2.5.RELEASE]
[INFO] [talledLocalContainer] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.0.8.RELEASE.jar:4.0.8.RELEASE]
[INFO] [talledLocalContainer] 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.0.8.RELEASE.jar:4.0.8.RELEASE]
[INFO] [talledLocalContainer] 	at com.sun.proxy.$Proxy73.saveTable(Unknown Source) ~[na:na]
[INFO] [talledLocalContainer] 	at io.oasp.gastronomy.restaurant.tablemanagement.logic.impl.TablemanagementImpl.saveTable(TablemanagementImpl.java:81) ~[oasp4j-sample-core-dev-SNAPSHOT.jar:dev-SNAPSHOT]
[INFO] [talledLocalContainer] 	at io.oasp.gastronomy.restaurant.tablemanagement.service.impl.rest.TablemanagementRestServiceImpl.saveTable(TablemanagementRestServiceImpl.java:114) ~[oasp4j-sample-core-dev-SNAPSHOT.jar:dev-SNAPSHOT]
[INFO] [talledLocalContainer] 	at io.oasp.gastronomy.restaurant.tablemanagement.service.impl.rest.TablemanagementRestServiceImpl$$FastClassBySpringCGLIB$$7f399c91.invoke(<generated>) ~[spring-core-4.0.8.RELEASE.jar:dev-SNAPSHOT]
[INFO] [talledLocalContainer] 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.0.8.RELEASE.jar:4.0.8.RELEASE]
[INFO] [talledLocalContainer] 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:708) ~[spring-aop-4.0.8.RELEASE.jar:4.0.8.RELEASE]
[INFO] [talledLocalContainer] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.0.8.RELEASE.jar:4.0.8.RELEASE]
[INFO] [talledLocalContainer] 	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:98) ~[spring-tx-4.0.8.RELEASE.jar:4.0.8.RELEASE]
[INFO] [talledLocalContainer] 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262) ~[spring-tx-4.0.8.RELEASE.jar:4.0.8.RELEASE]
[INFO] [talledLocalContainer] 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:95) ~[spring-tx-4.0.8.RELEASE.jar:4.0.8.RELEASE]
[INFO] [talledLocalContainer] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.0.8.RELEASE.jar:4.0.8.RELEASE]
[INFO] [talledLocalContainer] 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:644) ~[spring-aop-4.0.8.RELEASE.jar:4.0.8.RELEASE]
[INFO] [talledLocalContainer] 	at io.oasp.gastronomy.restaurant.tablemanagement.service.impl.rest.TablemanagementRestServiceImpl$$EnhancerBySpringCGLIB$$58a2b211.saveTable(<generated>) ~[spring-core-4.0.8.RELEASE.jar:dev-SNAPSHOT]
[INFO] [talledLocalContainer] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_76]
[INFO] [talledLocalContainer] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_76]
[INFO] [talledLocalContainer] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_76]
[INFO] [talledLocalContainer] 	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_76]
[INFO] [talledLocalContainer] 	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181) ~[cxf-core-3.0.3.jar:3.0.3]
[INFO] [talledLocalContainer] 	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97) ~[cxf-core-3.0.3.jar:3.0.3]
[INFO] [talledLocalContainer] 	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200) [cxf-rt-frontend-jaxrs-3.0.3.jar:3.0.3]
```


The same errors I'm getting on my local machine. They should be analysed separately in the application.

**Comment by oelsabba** [comment]
@sobkowiak I am wondering about the test of `TableManagementRestServiceTest.markTableAsTest`.
I think all mark*As should have been removed (Please see #172). Thus, I suggest re-opening this issue. But, I think this only partially solves the problem.

**Comment by julianmetzler** [comment]
@oelsabba I think you're right, that test should be removed, but the real problem seems to be the HTTP 403 Forbidden response on many tests. They occur on creation of tables (*saveTable()*), but I don't get why the permissions seems to be okay.

**Comment by sobkowiak** [comment]
Problems with `Forbidden HTTP 403 Forbidden` in test cases are caused by wrong user/role assigbnebt in test data. I'm gonna correct this

**Comment by sobkowiak** [comment]
15 testcases ignored...  our itests don't look excellent. i propose to spend a bit more time to make them working...

**Comment by sobkowiak** [comment]
Please review my last commit.

**Comment by hohwille** [comment]
> I can find one process running on port 8143

I assume that our current approach is generally not reliable if processes remain hanging and get orphaned. We should probably try arquillian and see if this is a more reliable approach - see #189

**Comment by sobkowiak** [comment]
:+1: For me it's ok.

**Comment by hohwille** [comment]
I know this is a pain but we can not complete this till the end of the week for the release.
We also urgently need volunteers with e.g. Arquillian experience that can replace the current i-tests with nice and reliable tests.

**Comment by MarcoRose** [comment]
JEnkins and Travis currently working. Integration test strategy to be reworked with Spring Boot #232
