### ISSUE TITLE
sample: Missing table: Product_AUD

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#182]
Die Sample Anwendung ist kaputt:

```
Caused by: org.hibernate.HibernateException: Missing table: Product_AUD
        at org.hibernate.cfg.Configuration.validateSchema(Configuration.java:1335)
        at org.hibernate.tool.hbm2ddl.SchemaValidator.validate(SchemaValidator.java:155)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:525)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1859)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:852)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:845)
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:398)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:844)
        at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:152)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:338)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:318)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1613)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1550)
        ... 25 more
```

**Comment by hohwille** [comment]
Wenn Product mit @Audited markiert ist, müssen wir auch im Flyway die AUD Tabelle anlegen.

**Comment by oelsabba** [comment]
@hohwille 
Just a reminder:  the official language of the project is English :smile:

**Comment by hohwille** [comment]
uupps. I was not noticing that while writing this on the way... :smile:

**Comment by hohwille** [comment]
Removing @Audited does not help then you end up with
> Caused by: org.hibernate.HibernateException: Missing table: REVINFO

**Comment by hohwille** [comment]
From Martin Buch:

append to ```V0001__Create_schema.sql```:

> CREATE CACHED TABLE PUBLIC.PRODUCT_AUD(
    revtype TINYINT,
    description VARCHAR(255),
    name VARCHAR(255),
    pictureId BIGINT,
    alcoholic BOOLEAN,
    dtype VARCHAR(31) NOT NULL,
    id BIGINT NOT NULL,
    rev BIGINT NOT NULL
);
CREATE CACHED TABLE PUBLIC.REVINFO(
    id BIGINT NOT NULL generated by default as identity (start with 1),
    timestamp BIGINT NOT NULL,
    user VARCHAR(255)
);

**Comment by hohwille** [comment]
This is what @julianmetzler IMHO forgot to commit and push. Today I have not much time and julian will be back tomorrow. Sorry for inconvenience...

**Comment by hohwille** [comment]
seems to solve the problem. Thanks Martin!

**Comment by julianmetzler** [comment]
Sorry for inconvenience, from my understanding the 
database.hibernate.hbm2ddl.auto = update
property should result in hibernate create these tables on startup, which has worked on my tests.
But inserting the tables in the flyway migration is the cleaner solution anyway.

**Comment by hohwille** [comment]
Thanks for the info. So this is considered as fixed if the DDLs are correct. For future changes please also consider AUD tables in flyway.
