### ISSUE TITLE
Duplicated definition for: 'identifiedType' error

### ISSUE THREAD

**Issue by darkmanAmazigh** [oasp/oasp4j#524]
Hi,
When i try to excute my application under oasp using run as java appliation, i have this error : 

`org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 20 in XML document from class path resource [META-INF/cxf/cxf.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 20; columnNumber: 414; <Line 20, Column 414>: XML-24500: (Error) Can not build schema 'http://www.springframework.org/schema/context' located at 'http://www.springframework.org/schema/context/spring-context.xsd'
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:399) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:181) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:217) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromImportedResources(ConfigurationClassBeanDefinitionReader.java:346) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:142) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:333) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:677) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:519) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at fr.cc.suivireco.SpringBootApp.main(SpringBootApp.java:26) [classes/:na]
Caused by: org.xml.sax.SAXParseException: <Line 20, Column 414>: XML-24500: (Error) Can not build schema 'http://www.springframework.org/schema/context' located at 'http://www.springframework.org/schema/context/spring-context.xsd'
	at oracle.xml.parser.v2.XMLError.flushErrorHandler(XMLError.java:428) ~[xmlparserv2-12.1.0.2.jar:na]
	at oracle.xml.parser.v2.XMLError.flushErrors1(XMLError.java:290) ~[xmlparserv2-12.1.0.2.jar:na]
	at oracle.xml.parser.v2.NonValidatingParser.parseDocument(NonValidatingParser.java:415) ~[xmlparserv2-12.1.0.2.jar:na]
	at oracle.xml.parser.v2.XMLParser.parse(XMLParser.java:236) ~[xmlparserv2-12.1.0.2.jar:na]
	at oracle.xml.jaxp.JXDocumentBuilder.parse(JXDocumentBuilder.java:175) ~[xmlparserv2-12.1.0.2.jar:na]
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:76) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadDocument(XmlBeanDefinitionReader.java:429) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:391) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	... 21 common frames omitted
Caused by: oracle.xml.parser.schema.XSDException: Duplicated definition for: 'identifiedType'
	at oracle.xml.parser.schema.XSDBuilder.buildSchema(XSDBuilder.java:1113) ~[xmlparserv2-12.1.0.2.jar:na]
	at oracle.xml.parser.schema.XSDBuilder.build(XSDBuilder.java:664) ~[xmlparserv2-12.1.0.2.jar:na]
	at oracle.xml.parser.schema.XSDValidator.processSchemaLocation(XSDValidator.java:1060) ~[xmlparserv2-12.1.0.2.jar:na]
	at oracle.xml.parser.schema.XSDValidator.startElement(XSDValidator.java:665) ~[xmlparserv2-12.1.0.2.jar:na]
	at oracle.xml.parser.v2.NonValidatingParser.parseElement(NonValidatingParser.java:1588) ~[xmlparserv2-12.1.0.2.jar:na]
	at oracle.xml.parser.v2.NonValidatingParser.parseRootElement(NonValidatingParser.java:448) ~[xmlparserv2-12.1.0.2.jar:na]
	at oracle.xml.parser.v2.NonValidatingParser.parseDocument(NonValidatingParser.java:394) ~[xmlparserv2-12.1.0.2.jar:na]
	... 26 common frames omitted`

Any ideas plz?

**Comment by jomora** [comment]
@darkmanAmazigh you should provide additional information regarding the context of your problem.
- What do you mean with "my application"? Are you referring to the Restaurant sample application provided in this repository?
- Which IDE did you use?
- ...

**Comment by darkmanAmazigh** [comment]
Yes, this problem occure when i try to execute the SpringBoot Main application, 
But with tomcat that work fine,
isn't the correct way to execute the restaurant sample application ?

**Comment by jomora** [comment]
@darkmanAmazigh honestly, you have to provide __MORE__ information. 
Have you been able to start the application in the meantime?

**Comment by darkmanAmazigh** [comment]
My application have three module, and one of this module run is an spring boot batch app, i must produce a sample jar, but when i get this jar, and i try to execute them, i get this error, the same error occured when i run the module in main application,

      @SpringBootApplication(exclude = { EndpointAutoConfiguration.class,   ErrorMvcAutoConfiguration.class })
     // @SpringBootApplication
      @EnableGlobalMethodSecurity(jsr250Enabled = true)
       public class Application {

                    public static void main(String args[]) {

                                  SpringApplication.run(BatchConfiguration.class, args);

                    }
       }

**Comment by darkmanAmazigh** [comment]
When i remove the m2 file, and i run maven update, i have see, that's get spring-framework-bom with 5 version,

   4.0.4.RELEASE
   4.1.8.RELEASE
   4.2.2.RELEASE
   4.2.3.RELEASE
   4.3.6.RELEASE

it's normal ?
Thank you

**Comment by darkmanAmazigh** [comment]
i have load the project in github,
It works as it's independent of the parent project, but when I add it to the parent, I hold the error up "duplicate .."

**Comment by darkmanAmazigh** [comment]
That's not a conflict with spring boot tomcat ?

Djavax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl

The mother application uses a tomcat independent of that of spring boot

**Comment by jomora** [comment]
@darkmanAmazigh did you solve your issue in the meantime?

**Comment by darkmanAmazigh** [comment]
I have separated into two different project, and to execute the batch, I remove this line from the configuration of tomcat8.

       Djavax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl

**Comment by hohwille** [comment]
I am not sure if I got it correctly but I try to summarize:
* You created an app based on OASP
* You had one module where you mixed batch and server
* You are getting the exception from your initial comment on the top of this issue

There actual error is due a "broken" XML DOM implementation that interferes here so `cxf.xml` can not be parsed correctly. That file comes from Apache CXF which is our recommended service framework. The XML is correct but in your case parsed by a broken DOM parser. As you can read in your own stacktrace:
```
Caused by: oracle.xml.parser.schema.XSDException
```

you are for some reason using an oracle XML parser that seems to be buggy. Track down why you have this dependency. If you can, get rid of it.
Otherwise it seems you already found the workaround with the Java system property `javax.xml.parsers.DocumentBuilderFactory`.
As we did not introduce that oracle XML parser, there is nothing we can do about and no bug in OASP.
Hence I am closing this issue. I hope with my feedback I could however help you to understand and resolve your problems.
