### ISSUE TITLE
Receiving an error while running the command 'mvn spring-boot:run' command in OASP4J 2.4.0

### ISSUE THREAD

**Issue by kiran-vadla** [oasp/oasp4j#590]
As part of the testing of OASP4J 2.4.0 Release, was testing the command 'mvn spring-boot:run' in directory oasp4j/samples/server and received an error. Error details below. One can try this command in the branch 'develop-2.4.0' to reproduce this error. I have raised an issue with Spring Boot Team and the issue number is https://github.com/spring-projects/spring-boot/issues/9456  

Error Details :

**********************************************************************************************************
D:\dev-2.4.0\OASP4J-2.4.0-Release\oasp4j\samples\server>mvn spring-boot:run
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.oasp.java.samples:oasp4j-sample-server:war:dev-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.springframework.boot:spring-boot-maven-plugin is missing. @ io.oasp.java.samples:oasp4j-sample-server:[unknown-version], D:\dev-2.4.0\OASP4J-2.4.0-Release\oasp4j\samples\server\pom.xml, line 135, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building oasp4j-sample-server dev-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:1.5.4.RELEASE:run (default-cli) > test-compile @ oasp4j-sample-server >>>
[WARNING] The POM for io.oasp.java.samples:oasp4j-sample-core:jar:dev-SNAPSHOT is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO]
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ oasp4j-sample-server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] skip non existing resourceDirectory D:\dev-2.4.0\OASP4J-2.4.0-Release\oasp4j\samples\server\src\main\client\dist
[INFO]
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ oasp4j-sample-server ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ oasp4j-sample-server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\dev-2.4.0\OASP4J-2.4.0-Release\oasp4j\samples\server\src\test\resources
[INFO]
[INFO] --- flatten-maven-plugin:1.0.0:flatten (flatten) @ oasp4j-sample-server ---
[INFO] Generating flattened POM of project io.oasp.java.samples:oasp4j-sample-server:war:dev-SNAPSHOT...
[INFO]
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ oasp4j-sample-server ---
[INFO] No sources to compile
[INFO]
[INFO] <<< spring-boot-maven-plugin:1.5.4.RELEASE:run (default-cli) < test-compile @ oasp4j-sample-server <<<
[INFO]
[INFO] --- spring-boot-maven-plugin:1.5.4.RELEASE:run (default-cli) @ oasp4j-sample-server ---
[WARNING]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:527)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
        at io.oasp.gastronomy.restaurant.SpringBootApp.main(SpringBootApp.java:24)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.652 s
[INFO] Finished at: 2017-06-12T11:08:21+05:30
[INFO] Final Memory: 17M/218M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.5.4.RELEASE:run (default-cli) on project oasp4j-sample-server: An exception occurred while running. null: InvocationTargetException: org/springframework/boot/SpringApplication: org.springframework.boot.SpringApplication -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**********************************************************************************************************

Thanks,
@kiran-vadla

**Comment by kiran-vadla** [comment]
Closing the issue as it is addressed as part of PR #591

Thanks,
@kiran-vadla
